### ISSUE TITLE
Search input box should probably not be multiline?

### ISSUE THREAD

**Issue by alexrp** [neurocyte/flow#236]
I've noticed that, in the search input box (Ctrl-F), if I paste a string that has multiple lines, or even just a single line break at the end, it actually causes the input box to scroll. I can also erase the line break.

This seems like it might be unintentional? FWIW, in situations like this, `micro` just takes the first line and strips any line breaks.

**Comment by neurocyte** [comment]
I have fixed this by properly rendering control codes with unicode. I prefer this to banning control codes because I like to be able to search for them, especially NL and Tab. Btw, you can enter NL and Tab in the mini buffer with `ctrl+enter` and `ctrl+i` respectively, which I find pretty useful.

**Comment by alexrp** [comment]
Hmm, even after e39d9ed, if I copy a word with Ctrl-C from within Flow and then Ctrl-F + Ctrl-Shift-V, I still get the issue. It appears to only be a display issue, however; the search does actually find the word.

> Btw, you can enter NL and Tab in the mini buffer with `ctrl+enter` and `ctrl+i` respectively, which I find pretty useful.

This doesn't seem to work on my end FWIW.

**Comment by neurocyte** [comment]
I found (and fixed) an issue with bracketed paste eating \n.

**Comment by neurocyte** [comment]
> > Btw, you can enter NL and Tab in the mini buffer with `ctrl+enter` and `ctrl+i` respectively, which I find pretty useful.
> 
> This doesn't seem to work on my end FWIW - no characters seem to appear from either of those key combinations.

This seems to me like an issue in alacritty. There have been a few bugs in alacritty's kitty keyboard protocol support. Is your alacritty up to date? I've tested here with 0.15.1 and it works for me.

**Comment by alexrp** [comment]
I'm using WezTerm, though with the Kitty keyboard protocol disabled since its implementation seems to have quite a few bugs.

**Comment by alexrp** [comment]
Hmm, unfortunately the problem still reproduces for me even after 8355f14f62a1cf19710bb00ffbb2981e455395ca... 🤔
